schema_version = "1.0.0"

id = "propconverterv"
version = "1.2.0"
name = "PropConverter-V"
tagline = "Addon for automated prop conversion in GTA V that rely's on Sollumz extentsion"
maintainer = "LN"
type = "add-on"

website = "https://github.com/LN-Development/PropConverter-V"

tags = ["Import-Export"]

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2026 LN"]

[permissions]
files = "Import/export RAGE asset files. Save/load presets."
clipboard = "Copy/paste location and rotation of objects."
network = "Install dependencies."

